version: 2.1
orbs:
  python: circleci/python@0.3.0
jobs:
 build:
   docker:
     - image: circleci/python:latest
   steps:
     - checkout
     - run:
         name: 最初の一歩
         command: |
           echo 'Hello World!'
           echo 'This is the delivery pipeline'
