version: 2.1
orbs:
  python: circleci/python@0.3.0
jobs:
 build:
   docker:
     - image: circleci/python:latest
   working_directory: ~/Takashi_Python
   steps:
     - checkout
     - run:
         name: パイソンテスト
         command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            pipenv run python error.py test
  - store_test_results:
            path: test-results
