version: 2.1
orbs:
  python: circleci/python@0.3.0
jobs:
  build:
    working_directory: ~/Takashi_Python
    docker:
      - image: circleci/python:latest
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2 # サービスコンテナの指定方法を示す例
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
  steps: 
      - checkout
      - run:
         name: パイソンテスト
         command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            pipenv run python error.py test
      - store_test_results:
            path: test-results
