version: 2.1
orbs:
  python: circleci/python@0.3.0
jobs:
  workflow:
    working_directory: ~/Takashi_Python
    docker:
      - image: circleci/python:latest
  steps: 
      - checkout
      - job:
         name: pythontest
         command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            pipenv run python error.py test
